<?xml version="1.0" encoding="UTF-8" ?>
<Package name="Untitled" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="Import" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="" src=".DS_Store" />
        <File name="__init__" src="lib/requests/__init__.py" />
        <File name="_internal_utils" src="lib/requests/_internal_utils.py" />
        <File name="adapters" src="lib/requests/adapters.py" />
        <File name="api" src="lib/requests/api.py" />
        <File name="auth" src="lib/requests/auth.py" />
        <File name="cacert" src="lib/requests/cacert.pem" />
        <File name="certs" src="lib/requests/certs.py" />
        <File name="compat" src="lib/requests/compat.py" />
        <File name="cookies" src="lib/requests/cookies.py" />
        <File name="exceptions" src="lib/requests/exceptions.py" />
        <File name="hooks" src="lib/requests/hooks.py" />
        <File name="models" src="lib/requests/models.py" />
        <File name="README" src="lib/requests/packages/README.rst" />
        <File name="__init__" src="lib/requests/packages/__init__.py" />
        <File name="__init__" src="lib/requests/packages/chardet/__init__.py" />
        <File name="big5freq" src="lib/requests/packages/chardet/big5freq.py" />
        <File name="big5prober" src="lib/requests/packages/chardet/big5prober.py" />
        <File name="chardetect" src="lib/requests/packages/chardet/chardetect.py" />
        <File name="chardistribution" src="lib/requests/packages/chardet/chardistribution.py" />
        <File name="charsetgroupprober" src="lib/requests/packages/chardet/charsetgroupprober.py" />
        <File name="charsetprober" src="lib/requests/packages/chardet/charsetprober.py" />
        <File name="codingstatemachine" src="lib/requests/packages/chardet/codingstatemachine.py" />
        <File name="compat" src="lib/requests/packages/chardet/compat.py" />
        <File name="constants" src="lib/requests/packages/chardet/constants.py" />
        <File name="cp949prober" src="lib/requests/packages/chardet/cp949prober.py" />
        <File name="escprober" src="lib/requests/packages/chardet/escprober.py" />
        <File name="escsm" src="lib/requests/packages/chardet/escsm.py" />
        <File name="eucjpprober" src="lib/requests/packages/chardet/eucjpprober.py" />
        <File name="euckrfreq" src="lib/requests/packages/chardet/euckrfreq.py" />
        <File name="euckrprober" src="lib/requests/packages/chardet/euckrprober.py" />
        <File name="euctwfreq" src="lib/requests/packages/chardet/euctwfreq.py" />
        <File name="euctwprober" src="lib/requests/packages/chardet/euctwprober.py" />
        <File name="gb2312freq" src="lib/requests/packages/chardet/gb2312freq.py" />
        <File name="gb2312prober" src="lib/requests/packages/chardet/gb2312prober.py" />
        <File name="hebrewprober" src="lib/requests/packages/chardet/hebrewprober.py" />
        <File name="jisfreq" src="lib/requests/packages/chardet/jisfreq.py" />
        <File name="jpcntx" src="lib/requests/packages/chardet/jpcntx.py" />
        <File name="langbulgarianmodel" src="lib/requests/packages/chardet/langbulgarianmodel.py" />
        <File name="langcyrillicmodel" src="lib/requests/packages/chardet/langcyrillicmodel.py" />
        <File name="langgreekmodel" src="lib/requests/packages/chardet/langgreekmodel.py" />
        <File name="langhebrewmodel" src="lib/requests/packages/chardet/langhebrewmodel.py" />
        <File name="langhungarianmodel" src="lib/requests/packages/chardet/langhungarianmodel.py" />
        <File name="langthaimodel" src="lib/requests/packages/chardet/langthaimodel.py" />
        <File name="latin1prober" src="lib/requests/packages/chardet/latin1prober.py" />
        <File name="mbcharsetprober" src="lib/requests/packages/chardet/mbcharsetprober.py" />
        <File name="mbcsgroupprober" src="lib/requests/packages/chardet/mbcsgroupprober.py" />
        <File name="mbcssm" src="lib/requests/packages/chardet/mbcssm.py" />
        <File name="sbcharsetprober" src="lib/requests/packages/chardet/sbcharsetprober.py" />
        <File name="sbcsgroupprober" src="lib/requests/packages/chardet/sbcsgroupprober.py" />
        <File name="sjisprober" src="lib/requests/packages/chardet/sjisprober.py" />
        <File name="universaldetector" src="lib/requests/packages/chardet/universaldetector.py" />
        <File name="utf8prober" src="lib/requests/packages/chardet/utf8prober.py" />
        <File name="__init__" src="lib/requests/packages/idna/__init__.py" />
        <File name="codec" src="lib/requests/packages/idna/codec.py" />
        <File name="compat" src="lib/requests/packages/idna/compat.py" />
        <File name="core" src="lib/requests/packages/idna/core.py" />
        <File name="idnadata" src="lib/requests/packages/idna/idnadata.py" />
        <File name="intranges" src="lib/requests/packages/idna/intranges.py" />
        <File name="uts46data" src="lib/requests/packages/idna/uts46data.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/__init__.py" />
        <File name="_collections" src="lib/requests/packages/urllib3/_collections.py" />
        <File name="connection" src="lib/requests/packages/urllib3/connection.py" />
        <File name="connectionpool" src="lib/requests/packages/urllib3/connectionpool.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/contrib/__init__.py" />
        <File name="appengine" src="lib/requests/packages/urllib3/contrib/appengine.py" />
        <File name="ntlmpool" src="lib/requests/packages/urllib3/contrib/ntlmpool.py" />
        <File name="pyopenssl" src="lib/requests/packages/urllib3/contrib/pyopenssl.py" />
        <File name="socks" src="lib/requests/packages/urllib3/contrib/socks.py" />
        <File name="exceptions" src="lib/requests/packages/urllib3/exceptions.py" />
        <File name="fields" src="lib/requests/packages/urllib3/fields.py" />
        <File name="filepost" src="lib/requests/packages/urllib3/filepost.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/packages/__init__.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/packages/backports/__init__.py" />
        <File name="makefile" src="lib/requests/packages/urllib3/packages/backports/makefile.py" />
        <File name="ordered_dict" src="lib/requests/packages/urllib3/packages/ordered_dict.py" />
        <File name="six" src="lib/requests/packages/urllib3/packages/six.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py" />
        <File name="_implementation" src="lib/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py" />
        <File name="poolmanager" src="lib/requests/packages/urllib3/poolmanager.py" />
        <File name="request" src="lib/requests/packages/urllib3/request.py" />
        <File name="response" src="lib/requests/packages/urllib3/response.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/util/__init__.py" />
        <File name="connection" src="lib/requests/packages/urllib3/util/connection.py" />
        <File name="request" src="lib/requests/packages/urllib3/util/request.py" />
        <File name="response" src="lib/requests/packages/urllib3/util/response.py" />
        <File name="retry" src="lib/requests/packages/urllib3/util/retry.py" />
        <File name="ssl_" src="lib/requests/packages/urllib3/util/ssl_.py" />
        <File name="timeout" src="lib/requests/packages/urllib3/util/timeout.py" />
        <File name="url" src="lib/requests/packages/urllib3/util/url.py" />
        <File name="sessions" src="lib/requests/sessions.py" />
        <File name="status_codes" src="lib/requests/status_codes.py" />
        <File name="structures" src="lib/requests/structures.py" />
        <File name="utils" src="lib/requests/utils.py" />
        <File name="" src="lib/.DS_Store" />
        <File name="__init__" src="lib/watson_developer_cloud/__init__.py" />
        <File name="alchemy_data_news_v1" src="lib/watson_developer_cloud/alchemy_data_news_v1.py" />
        <File name="alchemy_language_v1" src="lib/watson_developer_cloud/alchemy_language_v1.py" />
        <File name="alchemy_vision_v1" src="lib/watson_developer_cloud/alchemy_vision_v1.py" />
        <File name="authorization_v1" src="lib/watson_developer_cloud/authorization_v1.py" />
        <File name="conversation_v1" src="lib/watson_developer_cloud/conversation_v1.py" />
        <File name="dialog_v1" src="lib/watson_developer_cloud/dialog_v1.py" />
        <File name="discovery_v1" src="lib/watson_developer_cloud/discovery_v1.py" />
        <File name="document_conversion_v1" src="lib/watson_developer_cloud/document_conversion_v1.py" />
        <File name="language_translation_v2" src="lib/watson_developer_cloud/language_translation_v2.py" />
        <File name="language_translator_v2" src="lib/watson_developer_cloud/language_translator_v2.py" />
        <File name="natural_language_classifier_v1" src="lib/watson_developer_cloud/natural_language_classifier_v1.py" />
        <File name="personality_insights_v2" src="lib/watson_developer_cloud/personality_insights_v2.py" />
        <File name="personality_insights_v3" src="lib/watson_developer_cloud/personality_insights_v3.py" />
        <File name="retrieve_and_rank_v1" src="lib/watson_developer_cloud/retrieve_and_rank_v1.py" />
        <File name="speech_to_text_v1" src="lib/watson_developer_cloud/speech_to_text_v1.py" />
        <File name="text_to_speech_v1" src="lib/watson_developer_cloud/text_to_speech_v1.py" />
        <File name="tone_analyzer_v3" src="lib/watson_developer_cloud/tone_analyzer_v3.py" />
        <File name="tradeoff_analytics_v1" src="lib/watson_developer_cloud/tradeoff_analytics_v1.py" />
        <File name="version" src="lib/watson_developer_cloud/version.py" />
        <File name="visual_recognition_v3" src="lib/watson_developer_cloud/visual_recognition_v3.py" />
        <File name="watson_developer_cloud_service" src="lib/watson_developer_cloud/watson_developer_cloud_service.py" />
        <File name="Tell_me_more_about_yourself" src="resources/Tell_me_more_about_yourself.wav" />
        <File name="how_tall_are_you" src="resources/how_tall_are_you.wav" />
        <File name="introduce_yourself" src="resources/introduce_yourself.wav" />
        <File name="what_are_your_ability" src="resources/what_are_your_ability.wav" />
        <File name="what_are_your_eye_colour" src="resources/what_are_your_eye_colour.wav" />
        <File name="who_are_your_best_friends" src="resources/who_are_your_best_friends.wav" />
        <File name="speech" src="resources/speech.wav" />
        <File name="speech1" src="resources/speech1.wav" />
    </Resources>
    <Topics />
    <IgnoredPaths />
</Package>
